[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
quinn = "0.11.8"
rmp-serde = "1.3.0"
rustls = "0.23.29"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }
zeroconf = "0.15.1"
